### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by alclonky** [whitesource/renovate#96]
Hi,
whats the roadmap for future pro releases?
We are waiting for a few bug fixes and in particular for the new regex manager feature.
Is there an way to manually update the renovate version inside the pro image?

Thx a lot

**Comment by alclonky** [comment]
Any updates or timeline for the release?

**Comment by rarkins** [comment]
Hi, sorry for the late reply. Aiming for end of this month.

**Comment by rarkins** [comment]
Hi, I'm preparing to publish the release candidate to Docker Hub soon - see #107 for the Draft PR to update this repo's documentation and examples. If you have the bandwidth to help me verify it this week or next, please email me on rhys@whitesourcesoftware.com so that I can send you a license key.

FYI there will be not much changes above the surface, just:
- A (free) license key will be used from now on to enable the image to run. It is verified locally and doesn't need to connect to any WhiteSource infrastructure to run
- The core Renovate will be updated to the latest v20 version for this release

**Comment by stuart-warren** [comment]
@YuraBeznos ?

**Comment by rarkins** [comment]
Sorry, I got my email address wrong originally above so if you've emailed me earlier today please send it again to the correct address, thanks.

**Comment by mikebryant** [comment]
Looking good for me so far :)

**Comment by rarkins** [comment]
Thanks. That's 3 separate thumbs up so far, so I think we're on track for GA next week.

**Comment by rarkins** [comment]
https://github.com/whitesource/renovate/releases/tag/1.0.0
